version: '3.8'
services:
  backend:
    build: ../[BE]GeniusOfInvestment # 여기에 Dockerfile이 위치한 디렉토리를 지정

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3307/toogui
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=0722
      - JASYPT_KEY=${JASYPT_KEY}
    depends_on:
      - mariadb
    ports:
      - "8080:8080" # 애플리케이션이 사용할 포트를 지정

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile # frontend의 Dockerfile이 있는 경로를 지정합니다.
    ports:
      - "5173:5173" # Nginx가 사용하는 포트를 호스트의 포트로 매핑합니다.
    volumes:
      - ./dist:/app/dist # 호스트의 현재 경로의 dist 폴더를 컨테이너의 /app/dist 폴더로 마운트합니다.


volumes:
  mariadb-data:
    driver: local
